### PR TITLE
MNT: Re-rendered with conda-smithy 3.1.12 and pinning 2018.10.16

### PR DESCRIPTION
**Pull request by ivirshup**
Checklist
* [x ] Used a fork of the feedstock to propose changes
* [x ] Bumped the build number (if the version is unchanged)
* [x ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

Precursor to #3, just to get linux builds working with newer version of R.

### CODE REVIEW

**Comment by ivirshup** [comment]
Could I get a rebuild on the `linux r-base 3.4.1`? Looks like a http error.

**Comment by bgruening** [comment]
triggered. Thanks @ivirshup!

**Comment by ivirshup** [comment]
Thanks @bgruening!

... but I might need another one ... for the long queue.

```
conda.CondaMultiError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/vs2015_runtime-14.0.25420-0.tar.bz2>
```

**Comment by bgruening** [comment]
Done.

**Pull request merged**
